### ISSUE TITLE
error: cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

### ISSUE THREAD

**Issue by rohitsaluja22** [TJCVRS/CRNN_Tensorflow#33]
#comment: Although all images in test/ directory are of the same size i.e. (100, 32), still I am getting following error, any help?

 error(detailed):

CRNN_Tensorflow$ python3 tools/write_text_features.py --dataset_dir test --save_dir newNPR/
Initialize the dataset provider ......
Dataset provider intialize complete
Start writing training tf records
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "tools/write_text_features.py", line 104, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir)
  File "tools/write_text_features.py", line 59, in write_features
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
  File "tools/write_text_features.py", line 59, in <listcomp>
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by daoqinzi** [comment]
maybe its you path is wrong

**Comment by hustzxl** [comment]
image  is  empty

**Comment by TJCVRS** [comment]
@rohitsaluja22 Maybe you should check your image path
