### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by daoqinzi** [TJCVRS/CRNN_Tensorflow#48]
@TJCVRS 您好，在执行“python tools/write_text_features.py --dataset_dir data/crnn_dataset --save_dir data/tfrecords_dir”的时候，跑出如下的错误：（数据集是自带的test_0*.jpg）

Initialize the dataset provider ......
data/crnn_dataset/Test/sample.txt
/home/aigo_/Desktop/CRNN_Tensorflow-master/data/crnn_dataset/test_01.jpg
shape (31, 116, 3)
/home/aigo_/Desktop/CRNN_Tensorflow-master/data/crnn_dataset/test_02.jpg
shape (31, 128, 3)
/home/aigo_/Desktop/CRNN_Tensorflow-master/data/crnn_dataset/test_03.jpg
shape (31, 83, 3)
Traceback (most recent call last):
  File "tools/write_text_features.py", line 106, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir)
  File "tools/write_text_features.py", line 52, in write_features
    normalization=None)
  File "/home/aigo_/Desktop/CRNN_Tensorflow-master/data_provider/data_provider.py", line 181, in __init__
    for tmp in info[:, 0]])
**ValueError: could not broadcast input array from shape (31,116,3) into shape (31)**

**Comment by FHainzl** [comment]
To my understanding, this error results from inputting different size images as training/testing data.

I fixed it by resizing my inputs before performing np.array(...) as follows:
In `data_provider.py`, replace

```
test_images = np.array([cv2.imread(ops.join(self.__test_dataset_dir, tmp), cv2.IMREAD_COLOR)
                               for tmp in info[:,0]]
```

with

```
test_images = [cv2.imread(ops.join(self.__test_dataset_dir, tmp), cv2.IMREAD_COLOR)
                               for tmp in info[:,0]]
test_images = np.array([cv2.resize(tmp, (100, 32)) for tmp in test_images])
```

and do the same for `train_images `a couple of lines below
