### ISSUE TITLE
Invalid argument: Input to reshape is a tensor with 39936 values, but the requested shape has 9600

### ISSUE THREAD

**Issue by hanglu** [TJCVRS/CRNN_Tensorflow#52]
I made a small data-set for training. when I ran train_shadownet.py, the error prints

INFO: 03-20 17:50:02: train_shadownet.py:187 * 139980221495104 Training from scratch
2018-03-20 17:50:03.162589: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 39936 values, but the requested shape has 9600
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_13, Reshape/shape)]]
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Input to reshape is a tensor with 39936 values, but the requested shape has 9600
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_13, Reshape/shape)]]
	 [[Node: Reshape/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_31_Reshape", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
INFO: 03-20 17:50:03: tf_logging.py:82 * 139976490587904 Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Input to reshape is a tensor with 39936 values, but the requested shape has 9600
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw/_13, Reshape/shape)]]
	 [[Node: Reshape/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_31_Reshape", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
2018-03-20 17:50:03.525702: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: You must feed a value for placeholder tensor 'phase' with dtype string
	 [[Node: phase = Placeholder[dtype=DT_STRING, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "tools/train_shadownet.py", line 302, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "tools/train_shadownet.py", line 204, in train_shadownet
    _, c, seq_distance, preds, gt_labels = sess.run([optimizer, cost, sequence_dist, decoded, input_labels])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'phase' with dtype string
	 [[Node: phase = Placeholder[dtype=DT_STRING, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'phase', defined at:
  File "tools/train_shadownet.py", line 302, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "tools/train_shadownet.py", line 77, in train_shadownet
    phase_tensor = tf.placeholder(dtype=tf.string, shape=None, name='phase')
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'phase' with dtype string
	 [[Node: phase = Placeholder[dtype=DT_STRING, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by TJCVRS** [comment]
@hanglu If you may put some details to locate the problem

**Comment by hanglu** [comment]
In the Chinese debug version, I use write_text_tfrecords.py to produce some training tf data, like train_feature_0_128.tfrecords. Then I run the tools/train_shadownet.py, it gave me error. 

W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Input to reshape is a tensor with 39936 values, but the requested shape has 9600

And the number "39936 " changed when I run the scripts again.

**Comment by hanglu** [comment]
The issue is from the version of python. When I used the python3 to make the training data, the problem was solved.
