### ISSUE TITLE
中文训练数据问题

### ISSUE THREAD

**Issue by zxy3416391** [TJCVRS/CRNN_Tensorflow#61]
你好，我使用真实的场景图片建了一套中文数据集，前面图片和sample.txt已经完成了，后面在建立tfrecord的时候出现问题了
Dataset provider intialize complete
Start writing training tf records
19268
602.125
  0%|                                                                            | 0/603 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "write_text_tfrecords.py", line 133, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir, batch_size=args.batch_size)
  File "write_text_tfrecords.py", line 83, in write_features
    imagenames=train_imagenames)
  File "/home/xyzhong/1work/CRNN_Tensorflow-chinese_version_debug/local_utils/data_utils.py", line 167, in write_features
    labels, length = self.encode_labels(labels)
  File "/home/xyzhong/1work/CRNN_Tensorflow-chinese_version_debug/local_utils/data_utils.py", line 121, in encode_labels
    encode_label = [self.char_to_int(char) for char in label]
  File "/home/xyzhong/1work/CRNN_Tensorflow-chinese_version_debug/local_utils/data_utils.py", line 121, in <listcomp>
    encode_label = [self.char_to_int(char) for char in label]
  File "/home/xyzhong/1work/CRNN_Tensorflow-chinese_version_debug/local_utils/data_utils.py", line 96, in char_to_int
    return self.__ord_2_index_map[str(temp)]
KeyError: '36153'
----------------------------------------------------------------------------------------------------------------------------------请问是需要在chinese_dict.txt里面加入我的数据集中的字吗，然后char_dict文件夹里面的json数据是会自动生成吗？不好意思，有点小白，这些问题没搞懂

**Comment by Snowty** [comment]
@zxy3416391 
你用这个分支下面的代码：https://github.com/TJCVRS/CRNN_Tensorflow/tree/chinese_version_debug
tools文件夹下面有establish_char_dict.py，用这个代码制作就好。
