### ISSUE TITLE
生成模型

### ISSUE THREAD

**Issue by CXY573** [TJCVRS/CRNN_Tensorflow#7]
在生成自己模型的时候，使用了train_shadownet.py出现了以下错误：

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: imagenames (data type: string) is required but could not be found.
	 [[Node: ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=2, Nsparse=1, Tdense=[DT_STRING, DT_STRING], dense_shapes=[[1], []], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/ExpandDims, ParseSingleExample/ParseExample/ParseExample/names, ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, ParseSingleExample/ParseExample/ParseExample/dense_keys_0, ParseSingleExample/ParseExample/ParseExample/dense_keys_1, ParseSingleExample/ParseExample/Const, ParseSingleExample/ParseExample/Const_1)]]
INFO: 11-06 15:56:13: tf_logging.py:82 * 140074667120384 Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: <unknown>, Feature: imagenames (data type: string) is required but could not be found.
	 [[Node: ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=2, Nsparse=1, Tdense=[DT_STRING, DT_STRING], dense_shapes=[[1], []], sparse_types=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](ParseSingleExample/ExpandDims, ParseSingleExample/ParseExample/ParseExample/names, ParseSingleExample/ParseExample/ParseExample/sparse_keys_0, ParseSingleExample/ParseExample/ParseExample/dense_keys_0, ParseSingleExample/ParseExample/ParseExample/dense_keys_1, ParseSingleExample/ParseExample/Const, ParseSingleExample/ParseExample/Const_1)]]
2017-11-06 15:56:14.055074: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055217: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055392: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055432: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055586: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055619: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055639: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055660: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055682: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055712: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055731: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055748: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2017-11-06 15:56:14.055777: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
Traceback (most recent call last):
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/cxy/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_shadownet.py", line 174, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "tools/train_shadownet.py", line 124, in train_shadownet
    [optimizer, cost, sequence_dist, decoded, input_labels, merge_summary_op])
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

Caused by op 'shuffle_batch', defined at:
  File "tools/train_shadownet.py", line 174, in <module>
    train_shadownet(args.dataset_dir, args.weights_path)
  File "tools/train_shadownet.py", line 51, in train_shadownet
    tensors=[images, labels, imagenames], batch_size=32, capacity=120, min_after_dequeue=100, num_threads=1)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 1220, in shuffle_batch
    name=name)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 791, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1342, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cxy/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): RandomShuffleQueue '_1_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_INT64, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]

有人知道怎么回事吗，看得我快崩溃了

**Comment by CXY573** [comment]
一直说找不到imagenames

**Comment by TJCVRS** [comment]
@CXY573 应该是你生成的tfrecords不对吧

**Comment by CXY573** [comment]
谢天谢地，你终于在线了，我按照你给我的树结构做的数据库，然后用write_features做成的train_tfrecord,但是一直说没有找到imagenames

![2017-11-06 16-37-11](https://user-images.githubusercontent.com/30207116/32432075-132c035a-c311-11e7-8b03-7b1cb92932cc.png)
![2017-11-06 16-37-30](https://user-images.githubusercontent.com/30207116/32432076-1358d1fa-c311-11e7-879a-6c55ca929ae1.png)
![2017-11-06 16-37-40](https://user-images.githubusercontent.com/30207116/32432077-1382c136-c311-11e7-9b32-2cfdbecfaea6.png)

**Comment by TJCVRS** [comment]
@CXY573 正常生成tfrecords了吗

**Comment by TJCVRS** [comment]
@CXY573 你的文件树不对，Train/1文件夹下面应该就是图像文件了，而不应该是文件夹

**Comment by CXY573** [comment]
跑起来了，但是原文章是端到端的，就是应该可以包含了检测，可以直接用场景文本数据集库，你有做这反面的打算吗～～～

**Comment by CXY573** [comment]
还有一个问题，关于生成的验证集，抽取了0.15train的图片生成的validation好像没有使用到

**Comment by TJCVRS** [comment]
@CXY573 CRNN模型只能用来做文字识别，不能用来做文字定位，关于文字定位问题可以关注CTPN等方法。

**Comment by CXY573** [comment]
当前的cost是不收敛的对吧？？？昨晚迭代了10000多次cost还是上下浮动

INFO: 11-07 11:06:58: train_shadownet.py:156 * 139862039930624 Epoch: 7656 cost=  4.131303 seq distance=  0.075354 train accuracy=  0.915471
INFO: 11-07 11:06:59: train_shadownet.py:156 * 139862039930624 Epoch: 7657 cost=  2.716055 seq distance=  0.051951 train accuracy=  0.923209
INFO: 11-07 11:07:00: train_shadownet.py:156 * 139862039930624 Epoch: 7658 cost=  3.153260 seq distance=  0.077296 train accuracy=  0.922704
INFO: 11-07 11:07:01: train_shadownet.py:156 * 139862039930624 Epoch: 7659 cost=  3.606867 seq distance=  0.096985 train accuracy=  0.859141
INFO: 11-07 11:07:02: train_shadownet.py:156 * 139862039930624 Epoch: 7660 cost=  6.018770 seq distance=  0.154824 train accuracy=  0.805866
INFO: 11-07 11:07:03: train_shadownet.py:156 * 139862039930624 Epoch: 7661 cost=  2.595614 seq distance=  0.081498 train accuracy=  0.939335
INFO: 11-07 11:07:03: train_shadownet.py:156 * 139862039930624 Epoch: 7662 cost=  5.197774 seq distance=  0.091293 train accuracy=  0.862700
INFO: 11-07 11:07:04: train_shadownet.py:156 * 139862039930624 Epoch: 7663 cost=  4.865756 seq distance=  0.106365 train accuracy=  0.820787
INFO: 11-07 11:07:05: train_shadownet.py:156 * 139862039930624 Epoch: 7664 cost=  2.131811 seq distance=  0.058160 train accuracy=  0.882192
INFO: 11-07 11:07:06: train_shadownet.py:156 * 139862039930624 Epoch: 7665 cost=  1.330232 seq distance=  0.041716 train accuracy=  0.944891
INFO: 11-07 11:07:07: train_shadownet.py:156 * 139862039930624 Epoch: 7666 cost=  4.455652 seq distance=  0.105035 train accuracy=  0.859809
INFO: 11-07 11:07:08: train_shadownet.py:156 * 139862039930624 Epoch: 7667 cost=  3.085151 seq distance=  0.073715 train accuracy=  0.862054
INFO: 11-07 11:07:09: train_shadownet.py:156 * 139862039930624 Epoch: 7668 cost=  5.611475 seq distance=  0.113787 train accuracy=  0.809001
INFO: 11-07 11:07:10: train_shadownet.py:156 * 139862039930624 Epoch: 7669 cost=  2.201789 seq distance=  0.055177 train accuracy=  0.918782
INFO: 11-07 11:07:11: train_shadownet.py:156 * 139862039930624 Epoch: 7670 cost=  2.262937 seq distance=  0.059178 train accuracy=  0.920944
INFO: 11-07 11:07:12: train_shadownet.py:156 * 139862039930624 Epoch: 7671 cost=  7.860060 seq distance=  0.108505 train accuracy=  0.859077
INFO: 11-07 11:07:13: train_shadownet.py:156 * 139862039930624 Epoch: 7672 cost=  2.215603 seq distance=  0.075495 train accuracy=  0.918976
INFO: 11-07 11:07:14: train_shadownet.py:156 * 139862039930624 Epoch: 7673 cost=  4.294900 seq distance=  0.120238 train accuracy=  0.877083
INFO: 11-07 11:07:15: train_shadownet.py:156 * 139862039930624 Epoch: 7674 cost=  3.154303 seq distance=  0.061931 train accuracy=  0.928521
INFO: 11-07 11:07:16: train_shadownet.py:156 * 139862039930624 Epoch: 7675 cost=  1.152368 seq distance=  0.052928 train accuracy=  0.943166
INFO: 11-07 11:07:16: train_shadownet.py:156 * 139862039930624 Epoch: 7676 cost=  0.796186 seq distance=  0.041667 train accuracy=  0.948958
INFO: 11-07 11:07:17: train_shadownet.py:156 * 139862039930624 Epoch: 7677 cost=  2.959803 seq distance=  0.085130 train accuracy=  0.894037
INFO: 11-07 11:07:18: train_shadownet.py:156 * 139862039930624 Epoch: 7678 cost=  1.364126 seq distance=  0.027557 train accuracy=  0.946401
INFO: 11-07 11:07:19: train_shadownet.py:156 * 139862039930624 Epoch: 7679 cost=  3.354763 seq distance=  0.071615 train accuracy=  0.907552

**Comment by TJCVRS** [comment]
@CXY573 数据量大的情况下这个模型需要迭代很多次loss值才能接近于0，我之前训练的模型迭代了20w次

**Comment by xrf116** [comment]
@CXY573
我已经集成了CTPN
不过目前，直接切图的识别率很低，正在想办法提高crnn的识别率，机器太差训练很恼火

**Comment by TJCVRS** [comment]
@xrf116 实际自然场景的直接使用Synth训练的模型识别效果应该不太好，应该得使用自己的数据集进行训练，欢迎分享训练结果。

**Comment by CXY573** [comment]
迭代了4万多次，还是这样，应该是过拟合了。用了你的model来进行培养，训练数据没变，二次训练应该是不好

**Comment by TJCVRS** [comment]
@CXY573 你可以不使用预训练参数，从头训练试试

**Comment by dehaisea** [comment]
我就是按照这种目录树组织的数据，并且也成功生成了tfrecord，但训练的时候还是遇到了同样的问题，请问你是怎么解决的 @CXY573
