### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wwxjtu** [TJCVRS/CRNN_Tensorflow#79]
您好，请问这个错误是什么原因呢？感谢感谢！

Traceback (most recent call last):
  File "drive/GoogleAI/CRNN_Tensorflow-master/tools/demo_shadownet.py", line 107, in <module>
    recognize(image_path=args.image_path, weights_path=args.weights_path)
  File "drive/GoogleAI/CRNN_Tensorflow-master/tools/demo_shadownet.py", line 68, in recognize
    decoder = data_utils.TextFeatureIO()
  File "drive/GoogleAI/CRNN_Tensorflow-master/local_utils/data_utils.py", line 240, in __init__
    self.__writer = TextFeatureWriter()
  File "drive/GoogleAI/CRNN_Tensorflow-master/local_utils/data_utils.py", line 161, in __init__
    super(TextFeatureWriter, self).__init__()
  File "drive/GoogleAI/CRNN_Tensorflow-master/local_utils/data_utils.py", line 26, in __init__
    self.__char_list = establish_char_dict.CharDictBuilder.read_char_dict(char_dict_path)
  File "drive/GoogleAI/CRNN_Tensorflow-master/local_utils/establish_char_dict.py", line 59, in read_char_dict
    assert ops.exists(dict_path)
AssertionError

**Comment by TJCVRS** [comment]
@wwxjtu 你可能没有获取到字典文件
