### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by zhuliqian** [TJCVRS/CRNN_Tensorflow#84]
Traceback (most recent call last):
  File "tools/demo_shadownet.py", line 22, in <module>
    from crnn_model import crnn_model
  File "/home/chase/crnn/crnn_model/crnn_model.py", line 17, in <module>
    from crnn_model import cnn_basenet
ImportError: cannot import name cnn_basenet

**Comment by TJCVRS** [comment]
@zhuliqian Add the module to your python path

**Comment by Tikam02** [comment]
how to and where we have add the path.
