### ISSUE TITLE
'test_feature_0_5000.tfrecords'

### ISSUE THREAD

**Issue by peterzhou1520** [TJCVRS/CRNN_Tensorflow#85]
I just clone the CRNN_Tensorflow-chinese_version and execute the test_shadownet.py, at first I found the tfrecords_list(which is defined in data_utils.py)=[]. so I changed the name of test_feature.tfreocrds to test_feature_0_0.tfrecords, then it gave me console as bellow:
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/CRNN_Tensorflow-chinese_version_debug/test_shadownet.py", line 190, in <module>
    test_shadownet(args.dataset_dir, args.weights_path, args.is_recursive)
  File "C:/Users/Administrator/Desktop/CRNN_Tensorflow-chinese_version_debug/test_shadownet.py", line 80, in test_shadownet
    for record in tf.python_io.tf_record_iterator(ops.join(dataset_dir, 'test_feature_0_15.tfrecords')):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 70, in tf_record_iterator
    compat.as_bytes(path), 0, compat.as_bytes(compression_type), status)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: data/tfrecords\test_feature_0_15.tfrecords : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4\udcceļ\udcfe\udca1\udca3

and it was caused by this sentence:
for record in tf.python_io.tf_record_iterator(ops.join(dataset_dir, 'test_feature_0_5000.tfrecords')):     test_sample_count += 1
what should I do to solve it?

**Comment by TJCVRS** [comment]
@peterzhou1520 Make sure the test tfrecords file exists
