### ISSUE TITLE
error python tools/write_text_features.py --dataset_dir data/ --save_dir data/

### ISSUE THREAD

**Issue by zhuliqian** [TJCVRS/CRNN_Tensorflow#91]
python tools/write_text_features.py --dataset_dir data/ --save_dir data/
Initialize the dataset provider ......
Traceback (most recent call last):
  File "tools/write_text_features.py", line 101, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir)
  File "tools/write_text_features.py", line 50, in write_features
    normalization=None)
  File "/home/chase/crnn/data_provider/data_provider.py", line 172, in __init__
    for tmp in info[:, 0]]
IndexError: too many indices for array

**Comment by TJCVRS** [comment]
@zhuliqian Maybe your training dataset was prepared incorrectly
